name: BE CD for Dev

on:
  push:
    branches: [ "develop" ]
    paths:
      - backend/**

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, linux, ARM64] # Self hosted runner 사용

      - name: Deploy to EC2
        run: sudo sh ~/deploy-script-dev.sh
