name: BE CD for Dev

on:
  workflow_dispatch:

  push:
    branches: [ "develop" ]
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY_NAME: ddangkong/ddangkong-api-dev

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting application-dev.yml
        run: |
          echo "${{ secrets.APPLICATION_DEV_YML }}" > ./src/main/resources/application-dev.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
      - run: cp ./build/libs/*.jar ./build/libs/app.jar
        with:
          name: build-artifact
          path: |
            ./build/libs/app.jar
            ./deploy/deploy-api-dev.yml

  deploy:
    needs: build
    runs-on: [ self-hosted, linux, ARM64 ] # Self hosted runner 사용

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        path: build-artifact
    - run: ls -R my-artifact
