name: BE CD for Dev

on:
  push:
    branches: [ "develop" ]
    paths:
      - backend/**

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, linux, ARM64] # Self hosted runner 사용

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_DEV_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_DEV_USERNAME }}@${{ secrets.EC2_DEV_IP }} sh ~/deploy-script-dev.sh

      - name: Cleanup
        run: |
          rm -f private_key.pem
