name: BE CD for Dev

on:
  pull_request:
    branches: [ "develop" ]
    paths:
      - backend/**

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, linux, ARM64] # Self hosted runner 사용

    steps:
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_DEV_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem ${{ secrets.EC2_DEV_USERNAME }}@${{ secrets.EC2_DEV_IP }} | sh deploy-script-dev.sh
          rm -f private_key.pem
