name: FE Build for admin

on:
  pull_request:
    branches:
      - develop
    paths:
      - "frontend-admin/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend-admin

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: frontend-admin/pnpm-lock.yaml

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend-admin

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        run: pnpm build
        working-directory: ./frontend-admin
